<a href="https://colab.research.google.com/github/marianoMarchetta1/ADD-UBA/blob/main/TI_EDA_AndD_IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
import os
import pandas as pd
import numpy as np

path = kagglehub.dataset_download("asaniczka/tmdb-movies-dataset-2023-930k-movies")
print("Path to dataset files:", path)

for f in os.listdir(path):
    print(f)

csv_path = os.path.join(path, "TMDB_movie_dataset_v11.csv")
movies_df = pd.read_csv(csv_path, low_memory=False)

Downloading to /root/.cache/kagglehub/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies/1060.archive...

100%|██████████| 253M/253M [00:01<00:00, 175MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies/versions/1060
TMDB_movie_dataset_v11.csv

In [ ]:
print(f"Dimensiones del dataset original: {movies_df.shape}")
movies_df.head()

Dimensiones del dataset original: (1495779, 24)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [ ]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495779 entries, 0 to 1495778
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1495779 non-null  int64
 1   title                 1495760 non-null  object
 2   vote_average          1495779 non-null  float64
 3   vote_count            1495779 non-null  int64
 4   status                1495779 non-null  object
 5   release_date          1142763 non-null  object
 6   revenue               1495779 non-null  int64
 7   runtime               1495779 non-null  int64
 8   adult                 1495779 non-null  bool
 9   backdrop_path         364736 non-null   object
 10  budget                1495779 non-null  int64
 11  homepage              153071 non-null   object
 12  imdb_id               686056 non-null   object
 13  original_language     1495779 non-null  object
 14  original_title        1495760 non-null  object
 15  overview              1147923 non-null  object
 16  popularity            1495779 non-null  float64
 17  poster_path           950699 non-null   object
 18  tagline               209430 non-null   object
 19  genres                825014 non-null   object
 20  production_companies  628036 non-null   object
 21  production_countries  757328 non-null   object
 22  spoken_languages      786557 non-null   object
 23  keywords              363189 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 263.9+ MB

In [ ]:
nulos = movies_df.isnull().sum()
porcentaje = (nulos / len(movies_df) * 100).round(2)

resumen_nulos = pd.DataFrame({
    'Nulos': nulos,
    'Porcentaje (%)': porcentaje
}).sort_values(by='Porcentaje (%)', ascending=False)

resumen_nulos[resumen_nulos['Nulos'] > 0]

                        Nulos  Porcentaje (%)
homepage              1342708           89.77
tagline               1286349           86.00
keywords              1132590           75.72
backdrop_path         1131043           75.62
production_companies   867743           58.01
imdb_id                809723           54.13
production_countries   738451           49.37
spoken_languages       709222           47.41
genres                 670765           44.84
poster_path            545080           36.44
release_date           353016           23.60
overview               347856           23.26
title                      19            0.00
original_title             19            0.00

In [ ]:
# Fechas
movies_df['release_date'] = pd.to_datetime(movies_df['release_date'], errors='coerce')

# Categóricas de baja cardinalidad
for col in ['status', 'original_language']:
    movies_df[col] = movies_df[col].astype('category')

In [ ]:
movies_df.dtypes

id                               int64
title                           object
vote_average                   float64
vote_count                       int64
status                        category
release_date            datetime64[ns]
revenue                          int64
runtime                          int64
adult                             bool
backdrop_path                   object
budget                           int64
homepage                        object
imdb_id                         object
original_language             category
original_title                  object
overview                        object
popularity                     float64
poster_path                     object
tagline                         object
genres                          object
production_companies            object
production_countries            object
spoken_languages                object
keywords                        object
dtype: object

In [ ]:
movies_df.describe()

,id,vote_average,vote_count,release_date,revenue,runtime,budget,popularity
count,1.495779e+06,1.495779e+06,1.495779e+06,1142763,1.495779e+06,1.495779e+06,1.495779e+06,1.495779e+06
mean,9.418425e+05,1.487509e+00,1.434695e+01,2001-12-01 17:55:31.578989056,6.085337e+05,4.314418e+01,2.301603e+05,9.605109e-01
min,2.000000e+00,0.000000e+00,0.000000e+00,1800-01-01 00:00:00,-1.200000e+01,-2.800000e+01,0.000000e+00,0.000000e+00
25%,5.171675e+05,0.000000e+00,0.000000e+00,1992-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,1.430000e-02
50%,9.675280e+05,0.000000e+00,0.000000e+00,2012-04-18 00:00:00,0.000000e+00,1.500000e+01,0.000000e+00,6.000000e-01
75%,1.376962e+06,0.000000e+00,0.000000e+00,2020-06-05 00:00:00,0.000000e+00,8.400000e+01,0.000000e+00,6.590000e-01
max,1.770856e+06,1.000000e+01,3.449500e+04,2099-12-31 00:00:00,5.000000e+09,1.440000e+04,1.000000e+09,2.994357e+03
std,5.001019e+05,2.817324e+00,2.777689e+02,NaN,1.982856e+07,6.039990e+01,5.267017e+06,6.633100e+00

In [ ]:
movies_df.describe(include=['category', 'bool'])

          status    adult original_language
count    1495779  1495779           1495779
unique         6        2               179
top     Released    False                en
freq     1438164  1347645            821652